### ISSUE TITLE
Support for Firefox 3.5

### ISSUE THREAD

**Issue by jasondavies** [jeresig/fireunit#5]
The maxVersion in install.rdf is listed as 3.1.\* so I assume 3.5 would be supported. Thought I may as well open an issue to track this.

**Comment by jaguire** [comment]
This should include support for Firefox 4 now as well.

**Comment by jaseemabid** [comment]
Firefox stable version in 6 now ! Need update.

**Comment by sudeshpoojari** [comment]
I think this project is in limbo since October 05, 2009. Will there be any more release or someone will have to fork it
